build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
      - Preview

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  NewLineAtEndOfFile:
    active: true
