build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

complexity:
  CyclomaticComplexMethod:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
      - Preview

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  NewLineAtEndOfFile:
    active: true
  UnusedPrivateMember:
    ignoreAnnotated:
      - Preview
  WildcardImport:
    active: false
